services:
  web-service:
    image: devopsdockeruh/simple-web-service
    container_name: simple-test
    command: server
    volumes:
      - ./text.log:/usr/src/app/text.log
    ports:
      - 8080:8080
