services:
  backend:
    build: backend
    container_name: backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres
  frontend:
    build: frontend
    container_name: frontend
  redis:
    image: redis
    container_name: redis
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    #volumes:
     # - ./database:/var/lib/postgresql
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
